- name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas folium

      - name: Génération de la carte des observations 24h
        env:
          METEOFRANCE_API_KEY: ${{ secrets.METEOFRANCE_API_KEY }}
        run: python generer_obs_24h.py

      - name: Envoi FTP vers le site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }} # <-- Attention à bien remettre TON nom de variable de serveur ici
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./wp-content/uploads/ # <-- À adapter
          exclude: |
            **/*
            !observations_pluie_24h.html
